from __future__ import annotations

import argparse
from pathlib import Path


SKILL_TEMPLATE = """# Repository Skill

Use this skill when contributing to this repository.

## Project signals
{signals}

## Working agreement
- Read existing docs before editing.
- Prefer small, reviewable changes.
- Run verification commands before declaring completion.
- Update tests or docs when behavior changes.
"""

CHECKLIST_TEMPLATE = """# Delivery Checklist

- [ ] Understand the issue and acceptance criteria.
- [ ] Inspect relevant files before changing code.
- [ ] Make the smallest useful change.
- [ ] Run tests, linters, or documented checks.
- [ ] Summarize changes and verification results.
"""

SCORECARD_TEMPLATE = """# Agent Ready Scorecard

Generated by `agent-ready`.

## Detected repository guidance
{signals}

## Suggested verification
```bash
{verification}
```

## Next improvements
- Document setup steps.
- Document test commands.
- Add issue and pull request templates.
- Keep agent skills current as the project evolves.
"""


def detect_signals(repo: Path) -> list[str]:
    candidates = [
        "README.md",
        "CONTRIBUTING.md",
        "pyproject.toml",
        "package.json",
        "go.mod",
        "Cargo.toml",
        ".github/ISSUE_TEMPLATE",
        ".github/PULL_REQUEST_TEMPLATE.md",
        "tests",
    ]
    found = [name for name in candidates if (repo / name).exists()]
    return found or ["No common guidance files detected yet."]


def guess_verification(repo: Path) -> str:
    if (repo / "pyproject.toml").exists():
        return "pytest"
    if (repo / "package.json").exists():
        return "npm test"
    if (repo / "go.mod").exists():
        return "go test ./..."
    if (repo / "Cargo.toml").exists():
        return "cargo test"
    return "echo 'Add project-specific verification commands'"


def write_file(path: Path, content: str, force: bool) -> bool:
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def init_repo(repo: Path, force: bool = False) -> list[Path]:
    repo = repo.resolve()
    signals = detect_signals(repo)
    signal_text = "\n".join(f"- {signal}" for signal in signals)
    verification = guess_verification(repo)

    outputs = {
        repo / ".agent" / "skills" / "repo.md": SKILL_TEMPLATE.format(signals=signal_text),
        repo / ".agent" / "checklists" / "delivery.md": CHECKLIST_TEMPLATE,
        repo / "AGENT_READY.md": SCORECARD_TEMPLATE.format(
            signals=signal_text,
            verification=verification,
        ),
    }

    written: list[Path] = []
    for path, content in outputs.items():
        if write_file(path, content, force):
            written.append(path)
    return written


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Make a repository agent-ready.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init = subparsers.add_parser("init", help="Generate agent guidance files.")
    init.add_argument("--repo", default=".", help="Repository path to initialize.")
    init.add_argument("--force", action="store_true", help="Overwrite existing generated files.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.command == "init":
        written = init_repo(Path(args.repo), force=args.force)
        if written:
            for path in written:
                print(f"created {path}")
        else:
            print("agent-ready files already exist; use --force to overwrite")
        return 0
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
